/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import com.sun.xml.internal.bind.v2.schemagen.xmlschema.Documentation;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class Analizador extends javax.swing.JFrame {
    //mis atributos
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    

    /**
     * Creates new form Analizador
     */
    public Analizador() {
        initComponents();
        
         this.setLocationRelativeTo(null);
         
        setTitle("ANALIZADOR");
    }
    
    /**
     * Método para abrir el archivo de entrada
     * @param archivo
     * @return 
     */
    public String AbrirArchivo(File archivo){
        String docu = "";
        try {
            entrada= new FileInputStream(archivo);
            int ascci;
            while ((ascci=entrada.read()) !=-1) {                
                char caracter=(char)ascci;
                docu+=caracter;
            }
        } catch (Exception e) {
        }
        return docu;
    }
    
    /**
     * Método para guardar archivo
     * @param archivo
     * @param docu
     * @return 
     */
    public String GuardarArchivo(File archivo, String docu){
        String mensaje= null;
        try {
            salida = new FileOutputStream(archivo);
            byte[] bytxt= docu.getBytes();
            salida.write(bytxt);
            mensaje="Archivo guardado";
        } catch (Exception e) {
        }
        return mensaje;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonHaciaE = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonAtxt = new javax.swing.JButton();
        jButtonGuardarA = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dubai Light", 0, 36)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 170, 640, 410);

        jButtonHaciaE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonHaciaE.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        jButtonHaciaE.setForeground(new java.awt.Color(0, 255, 0));
        jButtonHaciaE.setText("Salir");
        jButtonHaciaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHaciaEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHaciaE);
        jButtonHaciaE.setBounds(770, 280, 200, 80);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Analizador");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 10, 340, 40);

        jButtonAtxt.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAtxt.setFont(new java.awt.Font("Dubai Medium", 0, 36)); // NOI18N
        jButtonAtxt.setForeground(new java.awt.Color(0, 255, 0));
        jButtonAtxt.setText("Archivo de Texto");
        jButtonAtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtxtActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtxt);
        jButtonAtxt.setBounds(60, 70, 340, 60);

        jButtonGuardarA.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGuardarA.setFont(new java.awt.Font("Dubai Medium", 0, 36)); // NOI18N
        jButtonGuardarA.setForeground(new java.awt.Color(0, 255, 0));
        jButtonGuardarA.setText("Guardar Archivo");
        jButtonGuardarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarA);
        jButtonGuardarA.setBounds(430, 70, 300, 60);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FinesseGrande.png"))); // NOI18N
        getContentPane().add(lblImg);
        lblImg.setBounds(0, 0, 1810, 1300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHaciaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHaciaEActionPerformed
        // TODO add your handling code here:
      /*OpcionesFinales entrada3 = new OpcionesFinales();
        entrada3.show();
        entrada3.setSize(825, 866);
        dispose();*/
      System.exit(0);
      
    }//GEN-LAST:event_jButtonHaciaEActionPerformed

    private void jButtonGuardarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarAActionPerformed
        // TODO add your handling code here:
        if (seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION) {
            archivo=seleccionar.getSelectedFile();
            if (archivo.getName().endsWith("txt")) {
                String Documento= jTextArea1.getText();
                String mensaje = GuardarArchivo(archivo, Documento);
                if (mensaje!=null) {
                    JOptionPane.showMessageDialog(null, mensaje);
                    
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo No Compatible");
                    
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Guardar Documento de texto");
            }
        }

        //gTablero(6, 4);
    }//GEN-LAST:event_jButtonGuardarAActionPerformed

    private void jButtonAtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtxtActionPerformed
   
        if (seleccionar.showDialog(null, "Abrir")==JFileChooser.APPROVE_OPTION) {
            archivo=seleccionar.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("txt")) {
                String documento = AbrirArchivo(archivo);
                jTextArea1.setText(documento);
               
            }else{
                JOptionPane.showMessageDialog(null, "Archivo no disponible");
            }
            }
            
            
        }

    }//GEN-LAST:event_jButtonAtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtxt;
    private javax.swing.JButton jButtonGuardarA;
    private javax.swing.JButton jButtonHaciaE;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblImg;
    // End of variables declaration//GEN-END:variables
}
